logging:
  level:
    ROOT: INFO

server:
  port: 8082

paradox:
  nakadi:
    errorhandler:
      sqs:
        enabled: true
        queueUrl: https://sqs.eu-central-1.amazonaws.com/1234567890/app-failed-events
        region: eu-central-1
    defaults:
      nakadiUrl: http://localhost:8080
      nakadiTokenId: nakadi-event-stream-read
      zookeeperBrokers: 127.0.0.1:2181
      defaultConsumerName: default-consumer
      oauth2Enabled : false
      partitionCoordinatorProvider: simple
      eventsBatchLimit: 1
      eventsStreamTimeoutSeconds: 180
      eventsStreamLimit: 0
      eventsStreamKeepAliveLimit: 0
      eventsBatchTimeoutSeconds: 1

tokens:
  enableMock: true
  startAfterCreation: true
  accessTokenUri: https://token.example.com

  token-configuration-list:
    - tokenId:  nakadi-event-stream-read
      scopes: nakadi.event_stream.read
